-- XianGuanJia read-only integration and rental operations foundation.
-- Credentials and customer-private source values are never stored in this migration.

CREATE TABLE IF NOT EXISTS `xianyu_application` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `application_code` varchar(64) NOT NULL,
  `display_name` varchar(128) NOT NULL,
  `enabled` bit(1) NOT NULL DEFAULT b'0',
  `credential_reference` varchar(256) DEFAULT NULL,
  `authorization_status` varchar(32) NOT NULL DEFAULT 'UNKNOWN',
  `authorization_expires_at` datetime DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xianyu_application_tenant_code` (`tenant_id`, `application_code`),
  KEY `idx_xianyu_application_status` (`tenant_id`, `authorization_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='闲管家应用';

CREATE TABLE IF NOT EXISTS `xianyu_shop` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `application_id` bigint NOT NULL,
  `external_shop_id` varchar(128) NOT NULL,
  `shop_name` varchar(256) DEFAULT NULL,
  `authorization_status` varchar(32) NOT NULL DEFAULT 'UNKNOWN',
  `authorization_expires_at` datetime DEFAULT NULL,
  `guarantee_status` varchar(32) NOT NULL DEFAULT 'UNKNOWN',
  `source_updated_at` datetime DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xianyu_shop_tenant_application_external` (`tenant_id`, `application_id`, `external_shop_id`),
  KEY `idx_xianyu_shop_authorization` (`tenant_id`, `authorization_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='闲鱼授权店铺';
-- NOTE: live DBs must apply 20260724_007 — unique key becomes authorize_id (seller_id is not unique across brands).

CREATE TABLE IF NOT EXISTS `xianyu_raw_payload` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `source_type` varchar(64) NOT NULL,
  `source_identifier` varchar(128) NOT NULL,
  `payload_hash` char(64) NOT NULL,
  `schema_version` varchar(32) NOT NULL,
  `redaction_version` varchar(32) NOT NULL,
  `payload` longtext NOT NULL,
  `received_at` datetime NOT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xianyu_raw_payload_source_hash` (`tenant_id`, `source_type`, `source_identifier`, `payload_hash`),
  KEY `idx_xianyu_raw_payload_received` (`tenant_id`, `received_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='闲管家受限原始载荷';

CREATE TABLE IF NOT EXISTS `xianyu_product` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `shop_id` bigint NOT NULL,
  `external_product_id` varchar(128) NOT NULL,
  `title` varchar(512) DEFAULT NULL,
  `category_id` varchar(128) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'UNKNOWN',
  `source_updated_at` datetime DEFAULT NULL,
  `raw_payload_id` bigint DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xianyu_product_shop_external` (`tenant_id`, `shop_id`, `external_product_id`),
  KEY `idx_xianyu_product_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='闲鱼商品';

CREATE TABLE IF NOT EXISTS `xianyu_product_sku` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `product_id` bigint NOT NULL,
  `external_sku_id` varchar(128) NOT NULL DEFAULT '',
  `sku_name` varchar(512) DEFAULT NULL,
  `source_stock` int DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'UNKNOWN',
  `source_updated_at` datetime DEFAULT NULL,
  `raw_payload_id` bigint DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xianyu_sku_product_external` (`tenant_id`, `product_id`, `external_sku_id`),
  KEY `idx_xianyu_sku_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='闲鱼商品规格';

CREATE TABLE IF NOT EXISTS `xianyu_order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `shop_id` bigint NOT NULL,
  `external_order_id` varchar(128) NOT NULL,
  `external_product_id` varchar(128) DEFAULT NULL,
  `external_sku_id` varchar(128) DEFAULT NULL,
  `order_status` varchar(64) NOT NULL DEFAULT 'UNKNOWN',
  `pay_amount` int NOT NULL DEFAULT 0,
  `currency` varchar(16) NOT NULL DEFAULT 'CNY',
  `seller_remark` text,
  `remark_parse_version` varchar(32) DEFAULT NULL,
  `remark_parse_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `source_created_at` datetime DEFAULT NULL,
  `source_updated_at` datetime DEFAULT NULL,
  `raw_payload_id` bigint DEFAULT NULL,
  `conversion_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `rental_order_id` bigint DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xianyu_order_shop_external` (`tenant_id`, `shop_id`, `external_order_id`),
  KEY `idx_xianyu_order_updated` (`tenant_id`, `source_updated_at`, `external_order_id`),
  KEY `idx_xianyu_order_conversion` (`tenant_id`, `conversion_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='闲鱼订单';

CREATE TABLE IF NOT EXISTS `xianyu_after_sale` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `shop_id` bigint NOT NULL,
  `external_after_sale_id` varchar(128) NOT NULL,
  `external_order_id` varchar(128) NOT NULL,
  `after_sale_status` varchar(64) NOT NULL DEFAULT 'UNKNOWN',
  `refund_amount` int DEFAULT NULL,
  `amount_unit_status` varchar(32) NOT NULL DEFAULT 'UNCONFIRMED',
  `timeout_at` datetime DEFAULT NULL,
  `source_updated_at` datetime DEFAULT NULL,
  `raw_payload_id` bigint DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xianyu_after_sale_shop_external` (`tenant_id`, `shop_id`, `external_after_sale_id`),
  KEY `idx_xianyu_after_sale_status` (`tenant_id`, `after_sale_status`),
  KEY `idx_xianyu_after_sale_order` (`tenant_id`, `external_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='闲鱼售后';

CREATE TABLE IF NOT EXISTS `xianyu_push_event` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `event_type` varchar(64) NOT NULL,
  `dedupe_key` varchar(256) NOT NULL,
  `external_identifier` varchar(128) DEFAULT NULL,
  `processing_status` varchar(32) NOT NULL DEFAULT 'RECEIVED',
  `raw_payload_id` bigint NOT NULL,
  `last_error_code` varchar(64) DEFAULT NULL,
  `last_error_message` varchar(512) DEFAULT NULL,
  `processed_at` datetime DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xianyu_push_event_dedupe` (`tenant_id`, `dedupe_key`),
  KEY `idx_xianyu_push_event_status` (`tenant_id`, `processing_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='闲管家推送事件';

CREATE TABLE IF NOT EXISTS `xianyu_sync_cursor` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `shop_id` bigint NOT NULL,
  `resource_type` varchar(64) NOT NULL,
  `cursor_updated_at` datetime DEFAULT NULL,
  `cursor_external_id` varchar(128) DEFAULT NULL,
  `safe_upper_bound` datetime DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xianyu_cursor_shop_resource` (`tenant_id`, `shop_id`, `resource_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='闲管家同步游标';

CREATE TABLE IF NOT EXISTS `xianyu_sync_run` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `shop_id` bigint DEFAULT NULL,
  `resource_type` varchar(64) NOT NULL,
  `trigger_type` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'QUEUED',
  `window_start` datetime DEFAULT NULL,
  `window_end` datetime DEFAULT NULL,
  `received_count` int NOT NULL DEFAULT 0,
  `deduplicated_count` int NOT NULL DEFAULT 0,
  `succeeded_count` int NOT NULL DEFAULT 0,
  `review_required_count` int NOT NULL DEFAULT 0,
  `failed_count` int NOT NULL DEFAULT 0,
  `last_error_code` varchar(64) DEFAULT NULL,
  `last_error_message` varchar(512) DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `finished_at` datetime DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  KEY `idx_xianyu_sync_run_status` (`tenant_id`, `status`, `create_time`),
  KEY `idx_xianyu_sync_run_shop` (`tenant_id`, `shop_id`, `resource_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='闲管家同步执行记录';

CREATE TABLE IF NOT EXISTS `xianyu_alert` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `shop_id` bigint DEFAULT NULL,
  `alert_type` varchar(64) NOT NULL,
  `dedupe_key` varchar(256) NOT NULL,
  `severity` varchar(16) NOT NULL DEFAULT 'WARNING',
  `status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `source_identifier` varchar(128) DEFAULT NULL,
  `message` varchar(512) NOT NULL,
  `first_seen_at` datetime NOT NULL,
  `last_seen_at` datetime NOT NULL,
  `resolved_at` datetime DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xianyu_alert_dedupe` (`tenant_id`, `dedupe_key`),
  KEY `idx_xianyu_alert_status` (`tenant_id`, `status`, `severity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='闲管家运营告警';

CREATE TABLE IF NOT EXISTS `xianyu_product_mapping` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `shop_id` bigint NOT NULL,
  `external_product_id` varchar(128) NOT NULL,
  `external_sku_id` varchar(128) NOT NULL DEFAULT '',
  `equipment_model_code` varchar(128) DEFAULT NULL,
  `mapping_status` varchar(32) NOT NULL DEFAULT 'UNMAPPED',
  `mapping_note` varchar(512) DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_xianyu_mapping_product_sku` (`tenant_id`, `shop_id`, `external_product_id`, `external_sku_id`),
  KEY `idx_xianyu_mapping_status` (`tenant_id`, `mapping_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='闲鱼商品设备型号映射';

CREATE TABLE IF NOT EXISTS `rental_order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `order_no` varchar(64) NOT NULL,
  `source_type` varchar(32) NOT NULL,
  `source_order_id` varchar(128) DEFAULT NULL,
  `channel_order_id` bigint DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'REVIEW_REQUIRED',
  `rent_amount` int NOT NULL DEFAULT 0,
  `refund_amount` int NOT NULL DEFAULT 0,
  `billable_start_date` date DEFAULT NULL,
  `billable_end_date` date DEFAULT NULL,
  `occupy_start_date` date DEFAULT NULL,
  `occupy_end_date_exclusive` date DEFAULT NULL,
  `conversion_version` varchar(32) DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rental_order_order_no` (`tenant_id`, `order_no`),
  UNIQUE KEY `uk_rental_order_source` (`tenant_id`, `source_type`, `source_order_id`),
  KEY `idx_rental_order_status` (`tenant_id`, `status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租赁订单';

CREATE TABLE IF NOT EXISTS `rental_order_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `rental_order_id` bigint NOT NULL,
  `equipment_model_code` varchar(128) DEFAULT NULL,
  `source_product_id` varchar(128) DEFAULT NULL,
  `source_sku_id` varchar(128) DEFAULT NULL,
  `quantity` int NOT NULL DEFAULT 1,
  `rent_amount` int NOT NULL DEFAULT 0,
  `billable_start_date` date DEFAULT NULL,
  `billable_end_date` date DEFAULT NULL,
  `occupy_start_date` date DEFAULT NULL,
  `occupy_end_date_exclusive` date DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  KEY `idx_rental_item_order` (`tenant_id`, `rental_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租赁订单明细';

CREATE TABLE IF NOT EXISTS `rental_device` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `device_no` varchar(128) NOT NULL,
  `serial_number` varchar(128) DEFAULT NULL,
  `equipment_model_code` varchar(128) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'AVAILABLE',
  `warehouse_code` varchar(128) DEFAULT NULL,
  `purchase_amount` int DEFAULT NULL,
  `enabled` bit(1) NOT NULL DEFAULT b'1',
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rental_device_no` (`tenant_id`, `device_no`),
  UNIQUE KEY `uk_rental_device_serial` (`tenant_id`, `serial_number`),
  KEY `idx_rental_device_model_status` (`tenant_id`, `equipment_model_code`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租赁设备实例';

CREATE TABLE IF NOT EXISTS `rental_schedule` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `device_id` bigint NOT NULL,
  `rental_order_id` bigint DEFAULT NULL,
  `rental_order_item_id` bigint DEFAULT NULL,
  `schedule_type` varchar(32) NOT NULL DEFAULT 'RENTAL',
  `status` varchar(32) NOT NULL DEFAULT 'EFFECTIVE',
  `occupy_start_date` date NOT NULL,
  `occupy_end_date_exclusive` date NOT NULL,
  `idempotency_key` varchar(128) DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rental_schedule_idempotency` (`tenant_id`, `idempotency_key`),
  KEY `idx_rental_schedule_device_range` (`tenant_id`, `device_id`, `status`, `occupy_start_date`, `occupy_end_date_exclusive`),
  KEY `idx_rental_schedule_order` (`tenant_id`, `rental_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备占用排期';

CREATE TABLE IF NOT EXISTS `rental_device_assignment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `rental_order_id` bigint NOT NULL,
  `rental_order_item_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `schedule_id` bigint NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ASSIGNED',
  `idempotency_key` varchar(128) NOT NULL,
  `assigned_at` datetime NOT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rental_assignment_idempotency` (`tenant_id`, `idempotency_key`),
  UNIQUE KEY `uk_rental_assignment_schedule` (`tenant_id`, `schedule_id`),
  KEY `idx_rental_assignment_device` (`tenant_id`, `device_id`, `status`),
  KEY `idx_rental_assignment_item` (`tenant_id`, `rental_order_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租赁设备分配';

CREATE TABLE IF NOT EXISTS `rental_manual_review` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `review_type` varchar(64) NOT NULL,
  `source_type` varchar(64) NOT NULL,
  `source_identifier` varchar(128) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `reason_code` varchar(64) NOT NULL,
  `reason_message` varchar(512) DEFAULT NULL,
  `resolution_note` varchar(512) DEFAULT NULL,
  `resolved_by` bigint DEFAULT NULL,
  `resolved_at` datetime DEFAULT NULL,
  `creator` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rental_review_source_type` (`tenant_id`, `source_type`, `source_identifier`, `review_type`),
  KEY `idx_rental_review_status` (`tenant_id`, `status`, `review_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租赁人工复核';
