const PRE = 'wd'

export default {
  button: `${PRE}-button`,
  calendar: 'fc-calendar',
  cascader: 'fc-cascader',
  cell: `${PRE}-cell`,
  checkbox: 'fc-checkbox',
  datePicker: 'fc-date-picker',
  field: `${PRE}-input`,
  form: `${PRE}-form`,
  formItem: `${PRE}-form-item`,
  input: `${PRE}-input`,
  inputNumber: `${PRE}-input-number`,
  radio: 'fc-radio',
  rate: `${PRE}-rate`,
  select: 'fc-select',
  ApiSelect: 'fc-api-select',
  DeptSelect: 'fc-dept-select',
  DictSelect: 'fc-dict-select',
  UserSelect: 'fc-user-select',
  slider: `${PRE}-slider`,
  switch: `${PRE}-switch`,
  textarea: `${PRE}-textarea`,
  timePicker: 'fc-time-picker',
  treeSelect: 'fc-tree-select',
  TreeSelect: 'fc-tree-select',
  treeSelectMultiple: 'fc-tree-select',
  upload: 'fc-uploader',
  uploader: 'fc-uploader',
  uploadFile: 'fc-uploader',
  uploadImage: 'fc-uploader',
  uploadImages: 'fc-uploader',
  FileUpload: 'fc-uploader',
  ImageUpload: 'fc-uploader',
  ImagesUpload: 'fc-uploader',
}
