export const uiState = {
  locale: 'zh-CN',
  theme: 'light',
  screen: 'workbench',
  reviewState: 'populated',
};

export const isEnglish = () => uiState.locale === 'en';
export const pick = (zh, en) => (isEnglish() ? en : zh);

const domainReplacements = [
  ['商品映射缺失', 'Product mapping missing'],
  ['未找到租期', 'Rental period not found'],
  ['日期校验', 'Date validation'],
  ['渠道订单聚合', 'Channel order aggregate'],
  ['527 个开放复核项', '527 open review items'],
  ['173 个开放复核项', '173 open review items'],
  ['54 个开放复核项', '54 open review items'],
  ['1 个开放复核项', '1 open review item'],
  ['60 个开放告警', '60 open alerts'],
  ['8 个开放告警', '8 open alerts'],
  ['3 个开放告警', '3 open alerts'],
  ['闲鱼售后', 'Xianyu after-sale'],
  ['发货日期汇总', 'Shipment-date aggregate'],
  ['命中 21 个渠道订单', '21 channel orders matched'],
  ['6 个店铺', '6 shops'],
  ['脱敏聚合', 'Masked aggregate'],
  ['渠道状态 12', 'Channel status 12'],
  ['待发货 151 单', '151 awaiting shipment'],
  ['渠道状态 21', 'Channel status 21'],
  ['已发货 213 单', '213 shipped'],
  ['管理端状态', 'Admin status'],
  ['归还日期汇总', 'Return-date aggregate'],
  ['计划归还 5 单', '5 planned returns'],
  ['租期字段', 'Rental-period fields'],
  ['计租中汇总', 'Active-rental aggregate'],
  ['当前计租 46 单', '46 currently billable'],
  ['07-29 快照', 'Jul 29 snapshot'],
  ['已建档设备', 'Registered devices'],
  ['2 台设备在租', '2 registered devices rented'],
  ['实例状态', 'Instance status'],
  ['复核原因', 'Review reason'],
  ['527 单', '527 orders'],
  ['仅 2 个型号已映射', 'Only 2 models mapped'],
  ['173 单', '173 orders'],
  ['54 单', '54 orders'],
  ['1 单', '1 order'],
  ['渠道订单', 'Channel orders'],
  ['管理端', 'Admin'],
  ['闲鱼', 'Xianyu'],
  ['累计', 'All-time'],
  ['今日', 'Today'],
  ['系统', 'System'],
  ['开放', 'Open'],
  ['SN 待补录', 'SN missing'],
  ['仅 A6 / P4P 已映射', 'Only A6 / P4P mapped'],
  ['未找到有效租期', 'No valid rental period found'],
  ['物流日期', 'Logistics date'],
  ['同步运行历史', 'Sync run history'],
  ['3 有效 / 3 失效', '3 valid / 3 invalid'],
  ['设备型号代码', 'Equipment model code'],
  ['已建档型号', 'Registered model'],
  ['库位待补录', 'Location not imported'],
  ['客户信息已脱敏', 'Customer data masked'],
  ['状态待校准', 'Status needs reconciliation'],
  ['计划归还', 'Planned returns'],
  ['渠道订单聚合', 'Channel order aggregate'],
  ['开放复核项', 'open review items'],
  ['开放告警', 'open alerts'],
  ['写入租赁订单时 creator 缺失', 'Missing creator while writing rental order'],
  ['近期服务端日志', 'Recent server log'],
  ['租期解析', 'Rental period parsing'],
  ['物流区间异常', 'Invalid logistics range'],
  ['商品映射', 'Product mapping'],
  ['缺少卖家备注', 'Missing seller note'],
  ['售后超时', 'After-sale timeout'],
  ['同步失败', 'Sync failure'],
  ['店铺授权', 'Shop authorization'],
  ['自动转换', 'Automatic conversion'],
  ['当前', 'Current'],
  ['近期', 'Recent'],
  ['已启用', 'Enabled'],
  ['立即可用', 'Available now'],
  ['计租', 'Billable'],
  ['占用', 'Occupied'],
  ['两个占用周期重叠', 'has two overlapping occupied periods'],
  ['卖家备注缺少完整租期', 'Seller note is missing a complete rental period'],
  ['演示店铺授权将在 7 天内到期', 'Demo shop authorization expires in 7 days'],
  ['演示店铺', 'Demo shop'],
  ['冲突：2 单重叠', 'Conflict: 2 overlapping orders'],
  ['灯光套装租赁', 'Lighting kit rental'],
  ['设备包装保障', 'Equipment protection case'],
  ['航拍作业', 'Aerial assignment'],
  ['发货准备', 'Shipment preparation'],
  ['回仓运输', 'Return transit'],
  ['维修锁定', 'Maintenance lock'],
  ['手持摄影机', 'Handheld camera'],
  ['微单相机', 'Mirrorless camera'],
  ['航拍无人机', 'Camera drone'],
  ['无线麦克风', 'Wireless microphone'],
  ['摄影附件', 'Camera accessory'],
  ['装备箱', 'Equipment case'],
  ['稳定器', 'Gimbal'],
  ['上海仓', 'Shanghai warehouse'],
  ['检修区', 'Service area'],
  ['张伟', 'Operator A'],
  ['李想', 'Operator B'],
  ['王强', 'Operator C'],
  ['待检测', 'Awaiting inspection'],
  ['待处理', 'Pending action'],
  ['维保中', 'In maintenance'],
  ['套装', 'kit'],
  ['检测', 'Inspection'],
  ['回仓', 'Return'],
  ['缺', 'Short '],
  ['区', ' zone'],
  ['排', ' row'],
  ['位', ' slot'],
  ['至', 'to'],
  ['天', 'days'],
  ['分钟', 'min'],
  ['小时', 'h'],
];

export function domainText(value) {
  if (!isEnglish() || typeof value !== 'string') return value;
  return domainReplacements.reduce((text, [source, target]) => text.replaceAll(source, target), value);
}

export const translations = {
  'zh-CN': {
    brand: '设备排期中心',
    warehouse: '全部已建档设备',
    today: '今天 2026-07-29 周三',
    category: '相机设备',
    shift: '早班 08:00-16:00',
    search: '搜索订单、SN、客户或运单号',
    synced: '脱敏快照：17:12',
    tenant: '捷租达',
    writeEnabled: '写入由服务端控制',
    navWorkbench: '今日工作台',
    navSchedule: '设备排期',
    navAvailability: '库存可用性',
    navOrders: '租赁订单',
    navDevices: '设备台账',
    navShipping: '发货交接',
    navExceptions: '异常中心',
    writesOff: '闲管家写操作已关闭',
    writesOffBody: '读取和排期不受影响，真实发货保持禁用。',
    loadingTitle: '正在读取运营数据',
    loadingBody: '当前页面和筛选会保留，不会清空已录入草稿。',
    emptyTitle: '当前筛选没有记录',
    emptyBody: '调整仓库、日期或设备组。空结果不等于同步失败。',
    errorTitle: '管理端数据暂时不可用',
    errorBody: '已保留页面状态，请检查网络后重试。',
    permissionTitle: '当前账号无权访问',
    permissionBody: '权限由管理端角色控制，请联系管理员。',
    retry: '重试',
    reviewMode: '原型状态',
    statePopulated: '有数据',
    stateLoading: '加载',
    stateEmpty: '空数据',
    stateError: '错误',
    statePermission: '无权限',
    stateDisabled: '写禁用',
    stateLogin: '登录页',
    mobileToday: '今日',
    mobileSchedule: '排期',
    mobileStock: '库存',
    mobileOrders: '订单',
    mobileShip: '发货',
    mobileAlerts: '异常',
  },
  en: {
    brand: 'Equipment Schedule Center',
    warehouse: 'Registered devices',
    today: 'Today · Wed, Jul 29, 2026',
    category: 'Camera equipment',
    shift: 'Morning 08:00-16:00',
    search: 'Search order, SN, customer, or waybill',
    synced: 'Masked snapshot: 17:12',
    tenant: 'Jiezuda',
    writeEnabled: 'Server-controlled writes',
    navWorkbench: 'Today',
    navSchedule: 'Schedule',
    navAvailability: 'Availability',
    navOrders: 'Rental orders',
    navDevices: 'Device ledger',
    navShipping: 'Outbound',
    navExceptions: 'Exceptions',
    writesOff: 'XianGuanJia writes are disabled',
    writesOffBody: 'Reads and scheduling remain available. Real shipment stays disabled.',
    loadingTitle: 'Loading operational data',
    loadingBody: 'The current page and filters are retained.',
    emptyTitle: 'No records for these filters',
    emptyBody: 'Adjust warehouse, dates, or equipment group.',
    errorTitle: 'Admin data is temporarily unavailable',
    errorBody: 'The page state is retained. Check the network and retry.',
    permissionTitle: 'This account cannot access the feature',
    permissionBody: 'Access is controlled by the admin role.',
    retry: 'Retry',
    reviewMode: 'Prototype state',
    statePopulated: 'Populated',
    stateLoading: 'Loading',
    stateEmpty: 'Empty',
    stateError: 'Error',
    statePermission: 'Permission',
    stateDisabled: 'Writes off',
    stateLogin: 'Login',
    mobileToday: 'Today',
    mobileSchedule: 'Schedule',
    mobileStock: 'Stock',
    mobileOrders: 'Orders',
    mobileShip: 'Ship',
    mobileAlerts: 'Alerts',
  },
};
