import type { LocalePreference } from '../preferences/preferenceModel';
import type { SafeErrorCategory } from '../../shared/lib/safeError';

type CopyMap = Record<string, string>;

const zhCN: CopyMap = {
  'page.eyebrow': 'LOGISTICS · TENANT OPERATIONS',
  'page.title': '物流配置与失败任务',
  'page.description': '管理租户级 Provider、承运商映射、异步失败任务和有界维护操作。浏览器只调用本地管理端 API。',
  'page.safety': '密钥不回显 · Provider 调用异步执行 · 回填默认演练',
  'page.noAccess': '当前账号没有任何物流运营权限。',
  'page.noAccessDetail': '请按查询、配置、重试、回填或清理职责分别申请权限。',
  'common.loading': '正在读取本地运营数据',
  'common.retry': '重试',
  'common.refresh': '刷新',
  'common.save': '保存',
  'common.saving': '正在保存',
  'common.cancel': '取消',
  'common.close': '关闭',
  'common.edit': '编辑',
  'common.delete': '删除',
  'common.deleting': '正在删除',
  'common.confirm': '确认执行',
  'common.noPermission': '无对应权限',
  'common.permissionTitle': '当前账号不能查询此面板',
  'common.permissionDetail': '该查询不会发起；请联系管理员授予独立的物流权限。',
  'common.errorTitle': '面板数据暂不可用',
  'common.error.network': '无法连接管理端服务，请检查网络后重试。',
  'common.error.authentication': '登录状态已失效，请重新登录。',
  'common.error.permission': '服务端拒绝了此操作，请刷新权限后重试。',
  'common.error.timeout': '管理端响应超时，请稍后重试。',
  'common.error.partial': '部分运营数据暂不可用，已保留成功结果。',
  'common.error.unknown': '操作未完成。界面不会显示第三方原始错误，请稍后重试。',
  'provider.title': '快递100租户配置',
  'provider.description': '公共开关与回调配置独立管理；可配置多组客户编码和 API Key，响应永不返回明文。',
  'provider.status': '配置状态',
  'provider.enabled': 'Provider 总开关',
  'provider.queryEnabled': '主动查询',
  'provider.subscribeEnabled': '订阅推送',
  'provider.callbackBaseUrl': '回调基础地址',
  'provider.minimumInterval': '最小查询间隔（秒）',
  'provider.resultVersion': '结果版本',
  'provider.lastVerified': '最近本地验证',
  'provider.neverVerified': '尚未验证',
  'provider.verify': '本地验证',
  'provider.verifying': '正在验证',
  'provider.secret.customerCode': '客户编码',
  'provider.secret.apiKey': 'API Key',
  'provider.secret.callbackSecret': '回调密钥',
  'provider.secret.configured': '已安全配置',
  'provider.secret.missing': '尚未配置',
  'provider.secret.keep': '保留现值',
  'provider.secret.replace': '替换',
  'provider.secret.clear': '清除',
  'provider.secret.placeholder': '输入新值，保存后立即清空',
  'provider.invalid': '请补全替换值，并确保查询间隔在 1800 至 86400 秒之间。',
  'provider.saved': 'Provider 配置已保存；所有密钥输入已清空。',
  'provider.verified': '本地配置验证通过。该结果不会自动开启 Provider。',
  'provider.verifyFailed': '本地配置不完整；未访问第三方网络。',
  'provider.credentials.title': '快递100凭据组',
  'provider.credentials.description': '每组包含客户编码和 API Key。Delivery 首次执行时稳定绑定一组启用凭据。',
  'provider.credentials.empty': '尚未配置凭据，Provider 无法执行订阅或查询。',
  'provider.credential.new': '新增凭据',
  'provider.credential.name': '凭据名称',
  'provider.credential.order': '排序',
  'provider.credential.enabled': '启用',
  'provider.credential.disabled': '停用',
  'provider.credential.secretState': '客户编码 {customer} · API Key {key}',
  'provider.credential.saved': '凭据已保存，密钥输入已清空。',
  'provider.credential.deleted': '凭据已删除；已绑定 Delivery 会在下次任务时重新选择。',
  'provider.credential.verified': '凭据本地验证通过，未访问第三方网络。',
  'provider.credential.verifyFailed': '凭据不完整，未访问第三方网络。',
  'provider.credential.deleteConfirm': '确认删除凭据“{name}”？',
  'provider.credential.operationFailed': '凭据操作未完成，请检查权限或输入后重试。',
  'mapping.title': '承运商映射',
  'mapping.description': '闲鱼来源编码 → 平台规范编码 → 快递100编码。',
  'mapping.new': '新建映射',
  'mapping.empty': '当前租户没有承运商映射',
  'mapping.emptyDetail': '缺少映射时发货仍可成功，但 Delivery 不会调用 Provider。',
  'mapping.source': '来源',
  'mapping.sourceCode': '来源编码',
  'mapping.canonical': '规范编码',
  'mapping.displayName': '显示名称',
  'mapping.provider': 'Provider',
  'mapping.providerCode': 'Provider 编码',
  'mapping.phone': '手机号要求',
  'mapping.state': '状态',
  'mapping.actions': '操作',
  'mapping.dialogNew': '新建承运商映射',
  'mapping.dialogEdit': '编辑承运商映射',
  'mapping.dialogDescription': '保存由后端按租户和来源编码校验幂等与冲突。',
  'mapping.invalid': '请填写全部必填编码和显示名称。',
  'mapping.saved': '承运商映射已保存。',
  'mapping.deleteTitle': '删除承运商映射？',
  'mapping.deleteDetail': '删除后，依赖该来源编码的新 Delivery 会进入待映射状态。',
  'mapping.deleted': '承运商映射已删除。',
  'tasks.title': '失败 Inbox / Outbox',
  'tasks.description': '只显示脱敏错误分类；安全重试仅重置本地任务状态。',
  'tasks.filter': '任务类型',
  'tasks.all': '全部',
  'tasks.limit': '最多读取',
  'tasks.empty': '当前没有失败任务',
  'tasks.emptyDetail': 'Inbox 与 Outbox 没有可安全重试的 FAILED、DEAD 或 RETRY_WAIT 记录。',
  'tasks.type': '类型',
  'tasks.delivery': 'Delivery',
  'tasks.event': '事件',
  'tasks.status': '状态',
  'tasks.retries': '重试次数',
  'tasks.nextAttempt': '下次尝试',
  'tasks.occurred': '发生时间',
  'tasks.error': '安全错误',
  'tasks.action': '操作',
  'tasks.retry': '安全重试',
  'tasks.retrying': '正在重排队',
  'tasks.retried': '任务已安全重排队。',
  'reconcile.title': 'Reconcile',
  'reconcile.description': '为未终态 Delivery 有界创建 RECONCILE Outbox，不同步等待 Provider。',
  'reconcile.limit': '本次上限',
  'reconcile.run': '提交 Reconcile',
  'reconcile.running': '正在提交',
  'reconcile.result': '已扫描 {requested} 条上限，创建 {count} 个异步任务。',
  'metrics.title': '物流运营指标',
  'metrics.description': '仅展示租户级计数、延迟和成功时间，不含运单、回调内容或凭据。',
  'metrics.empty': '当前没有物流运营指标',
  'metrics.emptyDetail': '本租户尚无 Delivery、异步任务或可统计状态。',
  'metrics.deliveries': 'Delivery 总数',
  'metrics.stale': '24 小时未同步',
  'metrics.failed': '失败任务',
  'metrics.retried': '发生过重试',
  'metrics.delay': 'Outbox 平均延迟',
  'metrics.seconds': '秒',
  'metrics.lastOutbox': '最近 Outbox 成功',
  'metrics.lastInbox': '最近 Inbox 成功',
  'metrics.distribution': '状态分布',
  'backfill.title': '历史 Delivery 回填',
  'backfill.description': '只基于本地 shipment/order 关系；默认 dry-run，单次最多 100 条。',
  'backfill.dryRun': '仅演练，不写入',
  'backfill.limit': '候选上限',
  'backfill.enqueue': '请求后续 Provider 任务',
  'backfill.enqueueHint': '后端当前仍会安全延后 Provider 入队，不会在回填事务中联网。',
  'backfill.run': '运行回填',
  'backfill.running': '正在检查',
  'backfill.confirmTitle': '执行非演练回填？',
  'backfill.confirmDetail': '该操作会创建或复用本地 Delivery，但不会默认调用 Provider。',
  'backfill.result': '候选 {candidates}，创建/复用 {created}，跳过 {skipped}。',
  'backfill.items': '回填结果明细',
  'cleanup.title': '技术数据保留清理',
  'cleanup.description': '只处理过期旧快照及已成功 Inbox/Outbox；不删除 Delivery、shipment 或订单。',
  'cleanup.dryRun': '仅演练，不删除',
  'cleanup.retention': '保留天数',
  'cleanup.limit': '本次总上限',
  'cleanup.run': '运行清理',
  'cleanup.running': '正在统计',
  'cleanup.confirmTitle': '执行非演练清理？',
  'cleanup.confirmDetail': '只删除超过保留期且符合后端审计策略的技术记录。',
  'cleanup.result': '轨迹 {traces}，Inbox {inbox}，Outbox {outbox}。',
  'maintenance.safeBoundary': '所有维护命令均由后端实施租户隔离、上限和审计约束。',
};

const en: CopyMap = {
  'page.eyebrow': 'LOGISTICS · TENANT OPERATIONS',
  'page.title': 'Logistics configuration and failed tasks',
  'page.description': 'Manage tenant provider settings, carrier mappings, failed async tasks, and bounded maintenance. The browser calls only local admin APIs.',
  'page.safety': 'Secrets never echoed · provider work stays async · backfill starts dry-run',
  'page.noAccess': 'This account has no logistics operations permission.',
  'page.noAccessDetail': 'Request the specific query, configuration, retry, backfill, or cleanup permission required for your role.',
  'common.loading': 'Loading local operations data',
  'common.retry': 'Retry',
  'common.refresh': 'Refresh',
  'common.save': 'Save',
  'common.saving': 'Saving',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.edit': 'Edit',
  'common.delete': 'Delete',
  'common.deleting': 'Deleting',
  'common.confirm': 'Confirm',
  'common.noPermission': 'Permission required',
  'common.permissionTitle': 'This account cannot query this panel',
  'common.permissionDetail': 'No request was made. Ask an administrator for the specific logistics permission.',
  'common.errorTitle': 'Panel data is unavailable',
  'common.error.network': 'Cannot reach the management service. Check the network and retry.',
  'common.error.authentication': 'The management session expired. Sign in again.',
  'common.error.permission': 'The server denied this operation. Refresh permissions and retry.',
  'common.error.timeout': 'The management service timed out. Retry shortly.',
  'common.error.partial': 'Some operations data is unavailable; successful sections were retained.',
  'common.error.unknown': 'The operation did not complete. Raw provider errors are never shown here.',
  'provider.title': 'Kuaidi100 tenant config',
  'provider.description': 'Manage shared switches and callback settings separately. Multiple customer-code and API-key pairs are supported without plaintext responses.',
  'provider.status': 'Config status',
  'provider.enabled': 'Provider enabled',
  'provider.queryEnabled': 'Active query',
  'provider.subscribeEnabled': 'Push subscription',
  'provider.callbackBaseUrl': 'Callback base URL',
  'provider.minimumInterval': 'Minimum query interval (seconds)',
  'provider.resultVersion': 'Result version',
  'provider.lastVerified': 'Last local verification',
  'provider.neverVerified': 'Never verified',
  'provider.verify': 'Verify locally',
  'provider.verifying': 'Verifying',
  'provider.secret.customerCode': 'Customer code',
  'provider.secret.apiKey': 'API key',
  'provider.secret.callbackSecret': 'Callback secret',
  'provider.secret.configured': 'Securely configured',
  'provider.secret.missing': 'Not configured',
  'provider.secret.keep': 'Keep current',
  'provider.secret.replace': 'Replace',
  'provider.secret.clear': 'Clear',
  'provider.secret.placeholder': 'Enter a new value; cleared after save',
  'provider.invalid': 'Complete each replacement and keep the interval between 1800 and 86400 seconds.',
  'provider.saved': 'Provider config saved. All secret inputs were cleared.',
  'provider.verified': 'Local configuration verified. Verification does not enable provider features.',
  'provider.verifyFailed': 'Local configuration is incomplete. No provider network call was made.',
  'provider.credentials.title': 'Kuaidi100 credentials',
  'provider.credentials.description': 'Each entry contains one customer code and API key pair. A delivery keeps a stable enabled credential assignment.',
  'provider.credentials.empty': 'No credential is configured. Provider subscription and query cannot run.',
  'provider.credential.new': 'New credential',
  'provider.credential.name': 'Credential name',
  'provider.credential.order': 'Sort order',
  'provider.credential.enabled': 'Enabled',
  'provider.credential.disabled': 'Disabled',
  'provider.credential.secretState': 'Customer {customer} · API key {key}',
  'provider.credential.saved': 'Credential saved. Secret inputs were cleared.',
  'provider.credential.deleted': 'Credential deleted. Bound deliveries will select another credential on their next task.',
  'provider.credential.verified': 'Credential verified locally without provider network access.',
  'provider.credential.verifyFailed': 'Credential is incomplete. No provider network call was made.',
  'provider.credential.deleteConfirm': 'Delete credential "{name}"?',
  'provider.credential.operationFailed': 'Credential operation failed. Check permissions and input, then retry.',
  'mapping.title': 'Carrier mappings',
  'mapping.description': 'Xianyu source code → canonical code → Kuaidi100 code.',
  'mapping.new': 'New mapping',
  'mapping.empty': 'No carrier mappings exist for this tenant',
  'mapping.emptyDetail': 'Shipment can still succeed, but new Delivery records stay mapping-required.',
  'mapping.source': 'Source',
  'mapping.sourceCode': 'Source code',
  'mapping.canonical': 'Canonical',
  'mapping.displayName': 'Display name',
  'mapping.provider': 'Provider',
  'mapping.providerCode': 'Provider code',
  'mapping.phone': 'Phone',
  'mapping.state': 'State',
  'mapping.actions': 'Actions',
  'mapping.dialogNew': 'Create carrier mapping',
  'mapping.dialogEdit': 'Edit carrier mapping',
  'mapping.dialogDescription': 'The backend enforces tenant-scoped idempotency and source-code conflicts.',
  'mapping.invalid': 'Complete every required code and display name.',
  'mapping.saved': 'Carrier mapping saved.',
  'mapping.deleteTitle': 'Delete this carrier mapping?',
  'mapping.deleteDetail': 'New deliveries using this source code will become mapping-required.',
  'mapping.deleted': 'Carrier mapping deleted.',
  'tasks.title': 'Failed Inbox / Outbox',
  'tasks.description': 'Only safe error categories are shown. Retry resets local task state only.',
  'tasks.filter': 'Task type',
  'tasks.all': 'All',
  'tasks.limit': 'Read limit',
  'tasks.empty': 'No failed tasks',
  'tasks.emptyDetail': 'Inbox and Outbox contain no retryable FAILED, DEAD, or RETRY_WAIT records.',
  'tasks.type': 'Type',
  'tasks.delivery': 'Delivery',
  'tasks.event': 'Event',
  'tasks.status': 'Status',
  'tasks.retries': 'Retries',
  'tasks.nextAttempt': 'Next attempt',
  'tasks.occurred': 'Occurred',
  'tasks.error': 'Safe error',
  'tasks.action': 'Action',
  'tasks.retry': 'Safe retry',
  'tasks.retrying': 'Requeueing',
  'tasks.retried': 'Task safely requeued.',
  'reconcile.title': 'Reconcile',
  'reconcile.description': 'Boundedly enqueue RECONCILE tasks for non-terminal deliveries without waiting for the provider.',
  'reconcile.limit': 'Run limit',
  'reconcile.run': 'Submit reconcile',
  'reconcile.running': 'Submitting',
  'reconcile.result': 'Requested limit {requested}; enqueued {count} async tasks.',
  'metrics.title': 'Logistics metrics',
  'metrics.description': 'Tenant counts, delay, and success times only. No waybills, callback payloads, or credentials.',
  'metrics.empty': 'No logistics metrics yet',
  'metrics.emptyDetail': 'This tenant has no Delivery, async task, or status data to aggregate.',
  'metrics.deliveries': 'Deliveries',
  'metrics.stale': 'Stale over 24h',
  'metrics.failed': 'Failed tasks',
  'metrics.retried': 'Retried tasks',
  'metrics.delay': 'Average Outbox delay',
  'metrics.seconds': 'sec',
  'metrics.lastOutbox': 'Last Outbox success',
  'metrics.lastInbox': 'Last Inbox success',
  'metrics.distribution': 'Status distribution',
  'backfill.title': 'Historical Delivery backfill',
  'backfill.description': 'Uses local shipment/order relations only. Defaults to dry-run and is capped at 100.',
  'backfill.dryRun': 'Dry-run only',
  'backfill.limit': 'Candidate limit',
  'backfill.enqueue': 'Request provider tasks later',
  'backfill.enqueueHint': 'The backend currently defers provider enqueue and never calls the provider inside backfill.',
  'backfill.run': 'Run backfill',
  'backfill.running': 'Checking',
  'backfill.confirmTitle': 'Run non-dry backfill?',
  'backfill.confirmDetail': 'This creates or reuses local Delivery records and does not call the provider by default.',
  'backfill.result': 'Candidates {candidates}, created/reused {created}, skipped {skipped}.',
  'backfill.items': 'Backfill result items',
  'cleanup.title': 'Technical retention cleanup',
  'cleanup.description': 'Only old snapshots and succeeded Inbox/Outbox records. Delivery, shipment, and order history are retained.',
  'cleanup.dryRun': 'Dry-run only',
  'cleanup.retention': 'Retention days',
  'cleanup.limit': 'Total limit',
  'cleanup.run': 'Run cleanup',
  'cleanup.running': 'Counting',
  'cleanup.confirmTitle': 'Run non-dry cleanup?',
  'cleanup.confirmDetail': 'Only technical records eligible under the backend retention policy are deleted.',
  'cleanup.result': 'Traces {traces}, Inbox {inbox}, Outbox {outbox}.',
  'maintenance.safeBoundary': 'The backend enforces tenant isolation, bounds, and audit rules for every maintenance command.',
};

export function operationsCopy(
  locale: LocalePreference,
  key: string,
  values?: Record<string, string | number>
) {
  let value = (locale === 'en' ? en : zhCN)[key] || zhCN[key] || key;
  Object.entries(values || {}).forEach(([name, replacement]) => {
    value = value.replaceAll(`{${name}}`, String(replacement));
  });
  return value;
}

export function operationsErrorCopy(
  locale: LocalePreference,
  error: SafeErrorCategory | null
) {
  return operationsCopy(locale, `common.error.${error || 'unknown'}`);
}

export function formatOperationsDateTime(
  locale: LocalePreference,
  value?: string | null
) {
  if (!value) return null;
  const normalized = value.includes('T') ? value : value.replace(' ', 'T');
  const date = new Date(normalized);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat(locale, {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date);
}

export function operationsCodeLabel(
  locale: LocalePreference,
  code?: string | null
) {
  if (!code) return locale === 'en' ? 'Not available' : '暂无';
  return code
    .toLowerCase()
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}
