DROP TABLE IF EXISTS rental_channel_product_sku_mapping;
DROP TABLE IF EXISTS rental_channel_product_rule;
DROP TABLE IF EXISTS rental_device_model;
DROP TABLE IF EXISTS xianyu_product_sku;
DROP TABLE IF EXISTS xianyu_product;
DROP TABLE IF EXISTS xianyu_shop;
DROP TABLE IF EXISTS xianyu_application;

CREATE TABLE xianyu_application (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    application_code varchar(64),
    display_name varchar(128),
    enabled boolean,
    base_url varchar(255),
    app_key varchar(128),
    app_secret varchar(255),
    webhook_base_url varchar(255),
    write_enabled boolean,
    job_enabled boolean,
    lookback_days int,
    overlap_minutes int,
    max_pages_per_shop int,
    page_size int,
    push_retry_stale_seconds int,
    push_retry_batch_size int,
    authorization_status varchar(32),
    authorization_expires_at timestamp,
    creator varchar(64) DEFAULT '',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '',
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id)
);

CREATE TABLE xianyu_shop (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    application_id bigint,
    external_shop_id varchar(128),
    xianyu_user_name varchar(128),
    authorize_id varchar(128),
    shop_name varchar(255),
    authorization_status varchar(32),
    authorization_expires_at timestamp,
    guarantee_status varchar(32),
    source_updated_at timestamp,
    creator varchar(64) DEFAULT '',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '',
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id)
);

CREATE TABLE xianyu_product (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    shop_id bigint NOT NULL,
    xgj_product_id varchar(128),
    xianyu_item_id varchar(128),
    external_product_id varchar(128),
    title varchar(512),
    category_id varchar(128),
    status varchar(32),
    source_updated_at timestamp,
    raw_payload_id bigint,
    creator varchar(64) DEFAULT '',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '',
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id)
);

CREATE TABLE xianyu_product_sku (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    product_id bigint NOT NULL,
    xgj_sku_id varchar(128),
    xianyu_sku_id varchar(128),
    external_sku_id varchar(128),
    sku_name varchar(255),
    source_stock int,
    status varchar(32),
    source_updated_at timestamp,
    raw_payload_id bigint,
    creator varchar(64) DEFAULT '',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '',
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id)
);

CREATE TABLE rental_device_model (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    category_id bigint,
    model_code varchar(64),
    model_name varchar(128),
    device_no_prefix varchar(32),
    next_sequence int,
    sort_order int,
    enabled boolean,
    lock_version int,
    creator varchar(64) DEFAULT '',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '',
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id)
);

CREATE TABLE rental_channel_product_rule (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    shop_id bigint NOT NULL,
    xianyu_item_id varchar(128) NOT NULL,
    xgj_product_id varchar(128),
    product_title_snapshot varchar(512),
    handling_policy varchar(32) NOT NULL,
    mapping_mode varchar(32) NOT NULL,
    single_device_model_id bigint,
    enabled boolean NOT NULL,
    rule_note varchar(512),
    lock_version int NOT NULL,
    creator varchar(64) DEFAULT '',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '',
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id),
    CONSTRAINT uk_rental_channel_rule_shop_item
        UNIQUE (tenant_id, shop_id, xianyu_item_id)
);

CREATE TABLE rental_channel_product_sku_mapping (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tenant_id bigint NOT NULL,
    product_rule_id bigint NOT NULL,
    product_sku_id bigint NOT NULL,
    xgj_sku_id varchar(128) NOT NULL,
    xianyu_sku_id varchar(128),
    device_model_id bigint NOT NULL,
    enabled boolean NOT NULL,
    lock_version int NOT NULL,
    creator varchar(64) DEFAULT '',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '',
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id),
    CONSTRAINT uk_rental_channel_sku_rule_xgj
        UNIQUE (tenant_id, product_rule_id, xgj_sku_id),
    CONSTRAINT uk_rental_channel_sku_rule_source
        UNIQUE (tenant_id, product_rule_id, product_sku_id),
    CONSTRAINT ck_reject_new_mapping
        CHECK (product_sku_id <> 201)
);
