-- Isolated integration-test legacy schema; new tables use the actual migration.
CREATE TABLE IF NOT EXISTS rental_device (id bigint PRIMARY KEY AUTO_INCREMENT,
device_no text,
legacy_device_no text,
serial_number text,
category_code text,
equipment_model_code text,
status text,
warehouse_code text,
purchase_amount int,
enabled bit(1),
source_type text,
source_biz_id bigint,
source_item_id bigint,
tenant_id bigint NOT NULL,
creator varchar(64) DEFAULT '',
updater varchar(64) DEFAULT '',
create_time datetime DEFAULT CURRENT_TIMESTAMP,
update_time datetime DEFAULT CURRENT_TIMESTAMP,
deleted bit(1) DEFAULT 0) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS rental_device_assignment (id bigint PRIMARY KEY AUTO_INCREMENT,
rental_order_id bigint,
rental_order_item_id bigint,
device_id bigint,
schedule_id bigint,
status text,
idempotency_key text,
assigned_at datetime,
returned_at datetime,
inspection_completed_at datetime,
inspection_result text,
return_note text,
tenant_id bigint NOT NULL,
creator varchar(64) DEFAULT '',
updater varchar(64) DEFAULT '',
create_time datetime DEFAULT CURRENT_TIMESTAMP,
update_time datetime DEFAULT CURRENT_TIMESTAMP,
deleted bit(1) DEFAULT 0) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS rental_schedule (id bigint PRIMARY KEY AUTO_INCREMENT,
device_id bigint,
rental_order_id bigint,
rental_order_item_id bigint,
schedule_type text,
status text,
occupy_start_date date,
occupy_end_date_exclusive date,
idempotency_key text,
tenant_id bigint NOT NULL,
creator varchar(64) DEFAULT '',
updater varchar(64) DEFAULT '',
create_time datetime DEFAULT CURRENT_TIMESTAMP,
update_time datetime DEFAULT CURRENT_TIMESTAMP,
deleted bit(1) DEFAULT 0) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS rental_device_lock (id bigint PRIMARY KEY AUTO_INCREMENT,
device_id bigint,
lock_type text,
reason text,
rental_order_id bigint,
rental_order_item_id bigint,
source_type text,
start_time datetime,
planned_end_time datetime,
released_at datetime,
released_by bigint,
release_reason text,
status text,
tenant_id bigint NOT NULL,
creator varchar(64) DEFAULT '',
updater varchar(64) DEFAULT '',
create_time datetime DEFAULT CURRENT_TIMESTAMP,
update_time datetime DEFAULT CURRENT_TIMESTAMP,
deleted bit(1) DEFAULT 0) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS rental_order (id bigint PRIMARY KEY AUTO_INCREMENT,
order_no text,
source_type text,
source_order_id text,
channel_order_id bigint,
customer_id bigint,
status text,
rent_amount bigint,
deposit_amount bigint,
refund_amount bigint,
settled_at datetime,
billable_start_date date,
billable_end_date date,
occupy_start_date date,
occupy_end_date_exclusive date,
expected_send_back_date date,
preparation_status text,
preparation_reason_code text,
preparation_updated_at datetime,
conversion_version text,
cancel_reason text,
tenant_id bigint NOT NULL,
creator varchar(64) DEFAULT '',
updater varchar(64) DEFAULT '',
create_time datetime DEFAULT CURRENT_TIMESTAMP,
update_time datetime DEFAULT CURRENT_TIMESTAMP,
deleted bit(1) DEFAULT 0) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS rental_order_item (id bigint PRIMARY KEY AUTO_INCREMENT,
rental_order_id bigint,
equipment_model_code text,
source_product_id text,
source_sku_id text,
quantity int,
quantity_source varchar(16) NOT NULL DEFAULT 'LEGACY',
rent_amount bigint,
billable_start_date date,
billable_end_date date,
occupy_start_date date,
occupy_end_date_exclusive date,
expected_send_back_date date,
tenant_id bigint NOT NULL,
creator varchar(64) DEFAULT '',
updater varchar(64) DEFAULT '',
create_time datetime DEFAULT CURRENT_TIMESTAMP,
update_time datetime DEFAULT CURRENT_TIMESTAMP,
deleted bit(1) DEFAULT 0) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS xianyu_order (id bigint PRIMARY KEY AUTO_INCREMENT,
shop_id bigint,
external_order_id text,
xgj_product_id text,
xianyu_item_id text,
xgj_sku_id text,
xianyu_sku_id text,
external_product_id text,
external_sku_id text,
preparation_status text,
preparation_reason_code text,
preparation_updated_at datetime,
order_status text,
pay_amount bigint,
currency text,
seller_remark text,
remark_parse_version text,
remark_parse_status text,
remark_parse_source text,
remark_parse_confidence decimal(20,2),
remark_parse_model text,
remark_parse_evidence_json text,
billable_start_date date,
billable_end_date date,
ship_date date,
receive_date date,
return_date date,
rental_period_status text,
rental_period_reason_code text,
source_created_at datetime,
source_updated_at datetime,
raw_payload_id bigint,
conversion_status text,
rental_order_id bigint,
detail_json text,
receiver_name text,
receiver_mobile text,
receiver_address text,
order_type int,
order_time datetime,
total_amount bigint,
pay_no text,
pay_time datetime,
refund_status int,
refund_amount bigint,
refund_time datetime,
waybill_no text,
express_code text,
express_name text,
express_fee bigint,
consign_type int,
consign_time datetime,
confirm_time datetime,
cancel_reason text,
cancel_time datetime,
buyer_nick text,
seller_name text,
goods_title text,
goods_quantity int,
goods_price bigint,
goods_json text,
xyb_seller_amount bigint,
tax_included bit(1),
idle_biz_type int,
pin_group_status int,
tenant_id bigint NOT NULL,
creator varchar(64) DEFAULT '',
updater varchar(64) DEFAULT '',
create_time datetime DEFAULT CURRENT_TIMESTAMP,
update_time datetime DEFAULT CURRENT_TIMESTAMP,
deleted bit(1) DEFAULT 0) ENGINE=InnoDB;